#encoding: utf-8

defaults: &defaults
  usable: true
  name: 云片网短信
  apikey: a3fa59da493d67ed21969c98953d285a
  tpl:
    take_medic: 2336456
    verify_code: 2335480
    medic_end: 2336458

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults