portal:
  code: 'PORTAL.ADMIN'  
  caption: 'XXX'
  path: '/admin/home#/'
  image: '/assets/index/doctor.png'
  sequence: '99.2'
headers:
  - code: 'ADMIN.A21'
    caption: '基础维护'
    path: ''
    sequence: '2'
    icon: 'fa-cogs'
    childs:
      - code: 'ADMIN.B211'
        caption: '接口文档'
        path: '#/applications/clinic'
        style_css: 'applications_clinic'
        icon: 'fa-bars'
        sequence: '11'
      - code: 'ADMIN.B219'
        caption: 'map 选点测试'
        path: '#/map/test'
        style_css: 'map_test'
        icon: 'fa-bars'
        sequence: '19'
  - code: 'ADMIN.A22'
    caption: '机构管理'
    path: '#/organizations/index'
    style_css: 'organizations_index'
    icon: 'fa-file-o'
    sequence: '20'
  - code: 'ADMIN.A23'
    caption: '用户管理'
    path: '#/users/index'
    style_css: 'users_index'
    icon: 'fa-file-o'
    sequence: '30'
  - code: 'ADMIN.A24'
    caption: '反馈管理'
    path: '#/feedbacks/index'
    style_css: 'feedbacks_index'
    icon: 'fa-file-o'
    sequence: '40'
