portal:
  code: 'PORTAL.HOSPITAL'  
  caption: 'XXX'
  path: '/hospital/home#/'
  image: '/assets/index/doctor.png'
  sequence: '99.2'
headers:
  - code: 'HOSPITAL.A1'
    caption: '接诊'
    path: '#/encounters/new'
    style_css: 'encounters_new'
    icon: 'fa-user-md'
    sequence: '1'
  - code: 'HOSPITAL.A2'
    caption: '我的患者'
    path: '#/patiens'
    style_css: 'patiens'
    icon: 'fa-users'
    sequence: '2'
  - code: 'HOSPITAL.A3'
    caption: '接诊统计'
    path: '#/encounters/index'
    style_css: 'encounters_index'
    icon: 'fa-bar-chart'
    sequence: '3'
  - code: 'HOSPITAL.A4'
    caption: '设置'
    icon: 'fa-cogs'
    sequence: '4'
    childs:
      - code: 'HOSPITAL.B41'
        caption: '药品模板管理'
        path: '#/sets/mtemplates/index'
        style_css: 'sets_mtemplates_index'
        icon: 'fa-tags'
        sequence: '1'
      - code: 'HOSPITAL.B49'
        caption: '初始设置'
        path: '#/sets/inis'
        style_css: 'sets_inis'
        icon: 'fa-cog'
        sequence: '9'
  # - code: 'HOSPITAL.A21'
  #   caption: '基础维护'
  #   path: ''
  #   sequence: '19'
  #   icon: 'fa-cogs'
  #   childs:
  #     - code: 'HOSPITAL.B211'
  #       caption: '目录管理'
  #       path: '#/projects/index'
  #       style_css: 'projects_index'
  #       icon: 'fa-bars'
  #       sequence: '11'
  # - code: 'HOSPITAL.A22'
  #   caption: '测试'
  #   path: '#/applications/new'
  #   style_css: 'applications_new'
  #   icon: 'fa-file-o'
  #   sequence: '20'
