portal:
  code: 'PORTAL.IMS'  
  caption: 'XXX'
  path: '/ims/order#'
  image: '/assets/admin/TM.png'
  sequence: '99.2'
headers:
  # - code: 'IMS.A21'
  #   caption: '基础维护'
  #   path: ''
  #   style_css: 'projects_index'
  #   sequence: '2'
  #   icon: 'fa-cogs'
  #   childs:
  #     - code: 'IMS.B211'
  #       caption: '目录管理'
  #       path: '#/projects/index'
  #       style_css: 'projects_index'
  #       icon: 'fa-bars'
  #       sequence: '11'
  - code: 'IMS.A23'
    caption: '药店'
    path: '#/order'
    style_css: 'order'
    icon: 'fa-tags'
    sequence: '20'

  - code: 'IMS.A26'
    caption: '药品管理'
    path: '#/items'
    style_css: 'items'
    icon: 'fa-tags'
    sequence: '22'
    
  - code: 'IMS.A24'
    caption: '报表'
    icon: 'fa-tasks'
    sequence: '21'
    childs:
      - code: 'IMS.B1'
        caption: '处方发药汇总-医院'
        path: '#/reports/dispensed_hospital'
        style_css: 'reports_dispensed_hospital'
        icon: 'fa-bar-chart'
        sequence: '1'
      - code: 'IMS.B2'
        caption: '处方退药汇总-医院'
        path: '#/reports/returned_hospital'
        style_css: 'reports_returned_hospital'
        icon: 'fa-bar-chart'
        sequence: '8'
      - code: 'IMS.B3'
        caption: '处方发药汇总-发药人'
        path: '#/reports/dispensed_name'
        style_css: 'reports_dispensed_name'
        icon: 'fa-bar-chart'
        sequence: '8'
      - code: 'IMS.B4'
        caption: '处方退药汇总-退药人'
        path: '#/reports/returned_name'
        style_css: 'reports_returned_name'
        icon: 'fa-bar-chart'
        sequence: '8'
      # - code: 'IMS.B410'
      #   caption: '处方药品汇总表'
      #   path: '#/reports/drug_report'
      #   style_css: 'reports_drug_report'
      #   icon: 'fa-bar-chart'
      #   sequence: '10'
  - code: 'IMS.A25'
    caption: '库存'
    icon: 'fa-tasks'
    sequence: '21'
    childs:
      - code: 'IMS.B10'
        caption: '库存表导入'
        path: '#/inv/stocks/exports'
        style_css: 'inv_stocks_exports'
        icon: 'fa-bar-chart'
        sequence: '1'
      - code: 'IMS.B11'
        caption: '库存查询'
        path: '#/inv/stocks/search_exports'
        style_css: 'inv_stocks_search_exports'
        icon: 'fa-bar-chart'
        sequence: '1'
      - code: 'IMS.B12'
        caption: '日志查询'
        path: '#/inv/refresh_logs/query_logs'
        style_css: 'refresh_logs_query'
        icon: 'fa-bar-chart'
        sequence: '1'
      