portal:
  code: 'PORTAL.IMS'  
  caption: 'XXX'
  path: '/ims/order#'
  image: '/assets/admin/TM.png'
  sequence: '99.2'
headers:
  # - code: 'IMS.A21'
  #   caption: '基础维护'
  #   path: ''
  #   style_css: 'projects_index'
  #   sequence: '2'
  #   icon: 'fa-cogs'
  #   childs:
  #     - code: 'IMS.B211'
  #       caption: '目录管理'
  #       path: '#/projects/index'
  #       style_css: 'projects_index'
  #       icon: 'fa-bars'
  #       sequence: '11'
  - code: 'IMS.A23'
    caption: '药店'
    path: '#/order'
    style_css: 'order'
    icon: 'fa-tags'
    sequence: '20'
  - code: 'IMS.A24'
    caption: '报表'
    icon: 'fa-tasks'
    sequence: '21'
    childs:
      - code: 'HOSPITAL.B41'
        caption: '处方发药汇总-医院'
        path: '#/reports/dispensed_hospital'
        style_css: 'reports_dispensed_hospital'
        icon: 'fa-bar-chart'
        sequence: '1'
      - code: 'HOSPITAL.B48'
        caption: '处方退药汇总-医院'
        path: '#/ims/reports/returned_hospital'
        style_css: 'ims_reports_returned_hospital'
        icon: 'fa-bar-chart'
        sequence: '8'
      - code: 'HOSPITAL.B410'
        caption: '处方药品汇总表'
        path: '#/ims/reports/drug_report'
        style_css: 'ims_reports_drug_report'
        icon: 'fa-bar-chart'
        sequence: '10'