portal:
  code: 'PORTAL.IMS'  
  caption: 'XXX'
  path: '/ims/home#/'
  image: '/assets/index/basic/MMM.png'
  sequence: '99.2'
headers:
  - code: 'IMS.A21'
    caption: '基础维护'
    path: ''
    sequence: '2'
    icon: 'fa-cogs'
    childs:
      - code: 'IMS.B211'
        caption: '目录管理'
        path: '#/projects/index'
        style_css: 'projects_index'
        icon: 'fa-bars'
        sequence: '11'
  - code: 'IMS.A22'
    caption: '测试'
    path: '#/applications/new'
    style_css: 'applications_new'
    icon: 'fa-file-o'
    sequence: '20'
  - code: 'IMS.A23'
    caption: '药店'
    path: '#/prescription/new'
    style_css: 'prescription_new'
    icon: 'fa-file-o'
    sequence: '20'