portal:
  code: 'PORTAL.IMS'  
  caption: 'XXX'
  path: '/ims/home#/'
  image: '/assets/index/doctor.png'
  sequence: '99.2'
headers:
  - code: 'IMS.A21'
    caption: '基础维护'
    path: ''
    sequence: '2'
    icon: 'fa-cogs'
    childs:
      - code: 'IMS.B211'
        caption: '目录管理'
        path: '#/projects/index'
        style_css: 'projects_index'
        icon: 'fa-bars'
        sequence: '11'
  - code: 'IMS.A23'
    caption: '药店'
    path: '#/prescription/new'
    style_css: 'prescription_new'
    icon: 'fa-file-o'
    sequence: '20'
    childs:
      - code: 'IMS.B231'
        caption: '药店'
        path: '#/prescription/new'
        style_css: 'prescription_new'
        icon: 'fa-bars'
        sequence: '21'
      - code: 'IMS.B23'
        caption: '药店设置'
        path: '#/order/settings'
        style_css: 'order_settings'
        icon: 'fa-bars'
        sequence: '21'