portal:
  code: 'PORTAL.IMS'  
  caption: 'XXX'
  path: '/ims/home#'
  image: '/assets/admin/TM.png'
  sequence: '99.2'
headers:
  - code: 'IMS.A21'
    caption: '基础维护'
    path: ''
    sequence: '2'
    icon: 'fa-cogs'
    childs:
      - code: 'IMS.B211'
        caption: '目录管理'
        path: '#/projects/index'
        style_css: 'projects_index'
        icon: 'fa-bars'
        sequence: '11'
  - code: 'IMS.A23'
    caption: '药店'
    path: '#/order'
    style_css: 'order'
    icon: 'fa-file-o'
    sequence: '20'
  # - code: 'IMS.A24'
  #   caption: '报表'
  #   path: '#/report'
  #   style_css: 'report'
  #   icon: 'fa-file-o'
  #   sequence: '21'