development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: notice_channel

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: mmp_production
