#encoding: utf-8

defaults: &defaults
  usable: true
  name: 贵州腾迈华希医疗
  app_id: 2018060860345111
  url: https://openapi.alipay.com/gateway.do
  api_name: alipay.trade.wap.pay
  app_pay_name: alipay.trade.app.pay
  refund_api: alipay.trade.refund
  format: JSON
  charset: utf-8
  sign_type: RSA2
  product_code: 2018060810537243
  version: 1.0
  domain_name: http://huaxi.tenmind.com
  notify_url: http://huaxi.tenmind.com/pay/alipay
  refund_notify_url: http://huaxi.tenmind.com/refund/alipay
  return_url: http://huaxi.tenmind.com
  public_key_root: <%= "#{Rails.root}/app/models/pay/alipay/alipay.pem" %>
  private_key_root: <%= "#{Rails.root}/app/models/pay/alipay/rsa_private_key.pem" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults