#encoding: utf-8

defaults: &defaults
  usable: true
  name: 贵州腾迈华希医疗
  appid: wx220fa8726920e2a2 #wx985d4b9d7b2784d2
  sign_type: MD5
  trade_type: MWEB
  spbill_ip: 58.16.181.25
  appsecret: 5fce5e7556d04a94eeca5700103c9609 #0e8523d092e28993b54b4b980116e832
  mchid: 1507477411 #1432526502
  pay_url: https://api.mch.weixin.qq.com/pay/unifiedorder
  refund_url: https://api.mch.weixin.qq.com/secapi/pay/refund
  cert_root: "/../../zhengshu/apiclient_cert.p12" #"/app/models/pay/wechat/apiclient_cert.p12" #"/../../zhengshu/apiclient_cert.p12"
  wap_name: 腾迈华希医药
  wap_url: http://huaxi.tenmind.com
  pay_key: GuiZhouTenmindHuaXiYiliaoHuJun18 #FeiShanJie88HaoTenmindGS20170222
  notify_url: http://huaxi.tenmind.com/pay/wechat
  refund_notify_url: http://huaxi.tenmind.com/refund/wechat
  health_total_fee: 19.9
  health_title: 华希订单
  health_cost_name: 健康小站
  awesome_setting: <%= "#{Rails.root}/config/setup/pay/wechat/apiclient_cert.p12" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults