class InitHospitalModels < ActiveRecord::Migration[5.1]
  def change
  	create_table :hospital_sets_departments, force: :cascade do |t|
	  	t.bigint "org_id", null: false, comment: "机构id"
	    t.string "name", limit: 20, default: "", null: false, comment: "科室名称"
	    t.string "jianpin", limit: 20, default: "", comment: "科室简称"
	    t.string "status", limit: 2, default: "", null: false, comment: "状态 N 新建   A 活动  O作废"
	    t.string "search_str", default: "", comment: "模糊查询字段"
	    t.datetime "created_at", null: false, comment: "创建时间"
	    t.datetime "updated_at", null: false, comment: "更新时间"
	    t.string "note", comment: "科室备注"
		end
   	create_table :hospital_sets_inis, force: :cascade do |t|
	    t.boolean "enable_print_pres", default: false, comment: "是否启用处方打印 1是true  0是false"
	    t.integer "uoperator_id", null: false, comment: "最后更新人 User.id"
	    t.text "print_pres_html", comment: "打印模板  写了触发器"
	    t.integer "org_id", null: false, comment: "机构id"
	    t.datetime "created_at", null: false, comment: "创建时间"
	    t.datetime "updated_at", null: false, comment: "更新时间"
	    t.integer "encounter_search_time", limit: 2, comment: "就诊查询字段"
	    t.bigint "prescription_audit_id", limit: 20, comment: "处分审核人 User"
		end
  	create_table :hospital_sets_mtemplates, force: :cascade do |t|
	    t.integer "org_id", null: false, comment: "机构id"
	    t.string "status", limit: 1, null: false, comment: "状态  新建N   默认A 可用  O废弃"
	    t.string "title", limit: 100, null: false, comment: "模板名称"
	    t.string "note", comment: "模板备注"
	    t.string "sharing_scope_code", limit: 1, null: false, comment: "共享代码"
	    t.string "sharing_scope_display", limit: 20, null: false, comment: "共享名称"
	    t.string "disease_code", limit: 20, null: false, comment: "病种代码"
	    t.string "disease_display", limit: 100, null: false, comment: "病种名称"
	    t.bigint "author_id", null: false, comment: "作者id"
	    t.string "author_display", limit: 50, null: false, comment: "作者名称"
	    t.bigint "location_id", null: false, comment: "科室id"
	    t.string "location_display", limit: 60, null: false, comment: "科室名称"
	    t.string "search_str", comment: "查询模糊字段"
	    t.datetime "created_at", null: false, comment: "创建时间"
	    t.datetime "updated_at", null: false, comment: "更新时间"
  	end
		create_table :hospital_diagnoses, force: :cascade do |t|
	    t.string "code", limit: 20, comment: "诊断编码"
	    t.string "display", limit: 100, null: false, comment: "诊断名称"
	    t.string "system", limit: 50, comment: "诊断编码系统  现在只支持ICD10"
	    t.string "status", limit: 1, default: "A", comment: "诊断状态 A 未确诊  E 已确诊"
	    t.integer "rank", limit: 1, comment: "诊断序号"
	    t.bigint "encounter_id", comment: "就诊id ( Hospital::Encounter )"
	    t.bigint "doctor_id", null: false, comment: "医生id（User）"
	    t.datetime "created_at", null: false, comment: "创建时间"
	    t.datetime "updated_at", null: false, comment: "更新时间"
	    t.bigint "prescription_id", comment: "处方id ( Hospital::Prescription )"
	    t.string "note", comment: "诊断备注"
	    t.datetime "fall_ill_at", comment: "发病时间"
	    t.integer "type_code", comment: "诊断类型 0 主要诊断  1 次要诊断"
	    t.string "type_display", limit: 10, comment: "诊断类型名称"
	    t.bigint "org_id", limit: 20, comment: "机构id"
  	end
	  create_table :hospital_encounters, force: :cascade do |t|
	    t.string "iden", limit: 18, comment: "身份证号"
	    t.string "name", limit: 60, null: false, comment: "姓名"
	    t.string "name_jp", limit: 60, comment: "姓名简拼"
	    t.string "name_wb", limit: 60, comment: "姓名五笔"
	    t.datetime "birth_date", comment: "出生日期"
	    t.integer "age", limit: 1, null: false, comment: "就诊年龄", unsigned: true
	    t.string "gender_code", limit: 2, null: false, comment: "性别编码"
	    t.string "gender_display", limit: 6, null: false, comment: "性别编码名称"
	    t.string "occupation_code", limit: 2, comment: "职业编码"
	    t.string "occupation_display", limit: 40, comment: "职业编码名称"
	    t.string "phone", limit: 11, null: false, comment: "手机号"
	    t.string "address", comment: "就诊时填写的地址  现居地址"
	    t.string "unit_name", comment: "工作单位名称（或者学校等）"
	    t.string "ua_address", comment: "单位地址（或者学校等）"
	    t.string "unit_phone", limit: 20, comment: "单位联系电话"
	    t.string "contact_name", limit: 60, comment: "联系人名称"
	    t.string "contact_phone", limit: 20, comment: "联系人电话"
	    t.bigint "hospital_oid", null: false, comment: "医院 机构id"
	    t.string "hospital_name", null: false, comment: "医院名称"
	    t.string "patient_domain_code", limit: 2, comment: "门诊或住院编码"
	    t.string "patient_domain_display", limit: 10, collation: "latin5_turkish_ci", comment: "门诊或住院编码名称"
	    t.string "patient_no", limit: 10, default: "", null: false, comment: "就诊号"
	    t.datetime "started_at", comment: "就诊时间"
	    t.datetime "created_at", null: false, comment: "数据创建时间"
	    t.datetime "updated_at", null: false, comment: "数据更新时间"
	    t.string "nation_code", limit: 4, comment: "民族编码"
	    t.string "nation_display", limit: 40, comment: "民族编码名称"
	    t.string "blood_code", limit: 2, comment: "血型编码"
	    t.string "blood_display", limit: 20, comment: "血型编码名称"
	    t.bigint "drugstore_location_id", comment: "药店id"
	    t.string "marriage_code", limit: 2, comment: "婚姻编码"
	    t.string "marriage_display", limit: 20, comment: "婚姻编码名称"
	    t.decimal "height", precision: 6, scale: 2, comment: "身高"
	    t.decimal "weight", precision: 6, scale: 2, comment: "体重"
	    t.bigint "person_id", comment: "实体人 Person id"
	    t.bigint "author_id", null: false, comment: "User 接诊医生"
	    t.text "photo", comment: "照片"
	    t.bigint "encounter_loc_id", limit: 20, comment: "就诊科室id"
	    t.string "encounter_loc_display", limit: 60, comment: "就诊科室名称"
	  end
  	create_table :hospital_irritabilities, force: :cascade do |t|
	    t.string "code", limit: 10, comment: "过敏编码"
	    t.string "display", limit: 40, null: false, comment: "过敏编码名称"
	    t.string "system", limit: 40, comment: "过敏编码系统"
	    t.string "status", limit: 1, comment: "过敏状态"
	    t.datetime "period_start", comment: "过敏开始时间"
	    t.bigint "data_entry_id", null: false, comment: "数据录入人 User"
	    t.bigint "person_id", null: false, comment: "过敏所属人 Person"
	    t.datetime "created_at", null: false, comment: "创建时间"
	    t.datetime "updated_at", null: false, comment: "更新时间"
	  end
  	create_table :hospital_orders, force: :cascade do |t|
	    t.integer "serialno", null: false, comment: "药品序号id"
	    t.string "title", limit: 120, null: false, comment: "医嘱名称"
	    t.string "specification", limit: 20, comment: "药品规格"
	    t.float "single_qty_value", limit: 24, null: false, comment: "单次数量的值"
	    t.string "single_qty_unit", limit: 30, comment: "单次数量的单位"
	    t.float "dose_value", limit: 24, null: false, comment: "单次剂量的值"
	    t.string "dose_unit", comment: "单次剂量的单位( 有些药品没有基本剂量的单位)"
	    t.string "route_code", limit: 10, null: false, comment: "途径编码"
	    t.string "route_display", limit: 30, null: false, comment: "途径编码名称"
	    t.string "frequency_code", limit: 10, null: false, comment: "频次编码"
	    t.string "frequency_display", limit: 30, null: false, comment: "频次编码名称"
	    t.integer "course_of_treatment_value", comment: "疗程的值"
	    t.string "course_of_treatment_unit", limit: 10, default: "天", comment: "疗程的单位（天）"
	    t.float "total_quantity", limit: 24, null: false, comment: "总量值"
	    t.string "unit", limit: 10, null: false, comment: "总量单位"
	    t.float "price", limit: 24, null: false, comment: "单价"
	    t.string "note", comment: "备注"
	    t.integer "status", default: 0, comment: "医嘱状态"
	    t.integer "order_type", default: 1, null: false, comment: "医嘱类型  1是药品医嘱  以后有其他的类型往后加"
	    t.bigint "encounter_id", comment: "就诊id  Hospital::Encounter"
	    t.datetime "created_at", null: false, comment: "创建时间"
	    t.datetime "updated_at", null: false, comment: "更新时间"
	    t.bigint "prescription_id", comment: "处方id Hospital::Prescription"
	    t.bigint "author_id", comment: "作者id User"
	    t.string "formul_code", limit: 8, comment: "剂型编码"
	    t.string "formul_display", limit: 20, comment: "剂型名称"
	    t.bigint "mtemplate_id", comment: "模板id Hospital::Sets::Mtemplate"
	    t.string "factory_name", limit: 60, comment: "厂家名称"
	    t.string "base_unit", limit: 30, comment: "基本单位"
	    t.decimal "mul", precision: 10, null: false, comment: "销售/基本单位的倍率"
	    t.decimal "measure_val", precision: 10, null: false, comment: " 最小计量值"
	    t.string "measure_unit", limit: 30, default: "", comment: "最小计量单位"
	    t.string "type_type", limit: 10, default: "instance", null: false, comment: "医嘱类型  instance 实例医嘱  template 模板医嘱"
	  end
  	create_table :hospital_prescriptions, force: :cascade do |t|
	    t.bigint "organization_id", null: false, comment: "处方所属机构id Admin::Organization"
	    t.integer "status", limit: 1, default: 1, null: false, comment: "处方状态:0 未审核,  1:已审核   2:待收费   3:已收费   4:已发药   8:已退药  9:已退费"
	    t.string "note", collation: "utf8_general_ci", comment: "处方备注"
	    t.string "type_code", limit: 10, null: false, collation: "utf8_general_ci", comment: "处方类型编码"
	    t.bigint "bill_id", comment: "账单id"
	    t.string "confidentiality_code", limit: 8, null: false, collation: "utf8_general_ci", comment: "权限编码"
	    t.bigint "doctor_id", null: false, comment: "医生id"
	    t.bigint "encounter_id", null: false, comment: "就诊id"
	    t.datetime "effective_start", null: false, comment: "处方有效时间开始"
	    t.datetime "effective_end", null: false, comment: "处方有效时间结束"
	    t.datetime "created_at", null: false, comment: "创建时间"
	    t.datetime "updated_at", null: false, comment: "更新时间"
	    t.string "type_display", limit: 40, null: false, collation: "utf8_general_ci", comment: "处方类型名称"
	    t.string "confidentiality_display", limit: 20, null: false, collation: "utf8_general_ci", comment: " 权限描述"
	    t.integer "prescription_no", comment: "处方号"
	    t.boolean "specialmark", default: false, comment: "特殊处方标记"
	    t.bigint "drug_store_id", comment: "药房id"
	    t.bigint "order_id", comment: "账单id"
	    t.string "tookcode", limit: 10, comment: "取药码"
	    t.bigint "author_id", null: false, comment: "作者id User"
	    t.bigint "auditor_id", comment: "审核人id User"
	    t.string "auditor_display", limit: 60, comment: "审核人姓名"
	    t.datetime "audit_at", comment: "审核时间"
	    t.bigint "abandonor_id", comment: "废弃人 User"
	    t.string "abandonor_display", limit: 60, comment: "废弃人姓名"
	    t.datetime "abandon_at", comment: "废弃时间"
	    t.bigint "delivery_id", comment: "发药人User"
	    t.string "delivery_display", limit: 60, comment: "发药人姓名"
	    t.datetime "delivery_at", comment: "发药时间"
	    t.bigint "create_bill_opt_id", comment: "账单创建人 User"
	    t.string "create_bill_opt_display", limit: 60, comment: "账单创建姓名"
	    t.datetime "bill_at", comment: "账单创建时间"
	    t.bigint "charger_id", comment: "收费人 User"
	    t.string "charger_display", limit: 60, comment: "收费人姓名"
	    t.datetime "charge_at", comment: "收费时间"
	    t.bigint "return_charge_opt_id", comment: "退费人 User"
	    t.string "return_charge_opt_display", limit: 60, comment: "退费人名称"
	    t.datetime "return_charge_at", comment: "退费时间"
	  end
  end
end
