#encoding: utf-8

defaults: &defaults
  normal_diet: 食物多样，谷类为主，粗细搭配 多吃蔬菜水果和薯类 每天吃奶类，大豆或其制品 常吃适量的鱼，禽，蛋和瘦肉 减少烹调油用量，吃清淡少盐膳食 食不过量，天天运动，保持健康体重 三餐分配要合理，零食要适当 每天足量饮水，合理选择饮料 如饮酒应限量 吃新鲜卫生的食物。
  bad_diet: 不吃早餐，晚餐过晚，饮水不足，饮酒过度，饮食过咸、过于油腻，暴饮暴食。
  motion_intensity: 运动量不少于5次/周，每次应不少于30分钟，每次运动在60～90分钟。为宜。
  sport_events: (1)根据空气污染情况，科学地选择锻炼的时间、地点。\n (2)注意不要意外受伤，注意场地、器械安全等。\n (3)运动前充分做好热身活动，运动后注意放松及保暖。\n (4)在运动过程中，要养成运动中补水的习惯，补水的原则是少量多次，建议喝运动饮料或纯净水。\n (5)在进行锻炼时要考虑身体患有某种疾病的因素。\n (6)运动后30分钟内不能进食。因为此时胃肠血管处于收缩状态，进食会影响消化。\n (7)若运动后精神状态好，睡眠好，食欲好，表明运动量合适;反之，若运动后非常疲倦，甚至感到头昏，周身无力，食欲差，睡眠差，则表明运动过度，需要适当减量。
  low: 
    desc: 低血压
    dietary_advice: 1） 高营养、易消化和富含维生素的饮食，强壮体质。2）适当饮用咖啡、可可和浓茶，有助于提高中枢神经系统的兴奋性，改善血管舒缩中枢功能，有利于提升血压和改善临床症状。此外，饮用蜂蜜或蜂王浆也有裨益。3）多吃莲子、桂圆、大枣、桑椹等果品，可养心益血、健脾补脑。4）选择适当的高钠、高胆固醇饮食。每日食盐用量需摄足12-15克，含胆固醇多的脑、肝、蛋、奶油、鱼卵、猪骨等食品，适量常吃，有利于提高血胆固醇浓度增加动脉紧张度，使血压上升。如伴有红细胞计数过低，血红蛋白不足的贫血症，宜适当多吃 富含蛋白质、铁、铜、叶酸、维生素B12、维生素C等“造血原料”的食物，诸如猪肝、蛋黄、 瘦肉、牛奶、鱼虾、贝类、大豆、豆腐、红糖及新鲜蔬菜、水果。纠正贫血，有利于增加心排血量，改善大脑的供血量，提高血压和消除血压偏低引起的不良症状。
  ideal: 
    desc: 理想血压
    dietary_advice: 食物多样，谷类为主，粗细搭配 多吃蔬菜水果和薯类 每天吃奶类，大豆或其制品 常吃适量的鱼，禽，蛋和瘦肉 减少烹调油用量，吃清淡少盐膳食 食不过量，天天运动，保持健康体重 三餐分配要合理，零食要适当 每天足量饮水，合理选择饮料 如饮酒应限量 吃新鲜卫生的食物。
  normal: 
    desc: 正常血压
    dietary_advice: 食物多样，谷类为主，粗细搭配 多吃蔬菜水果和薯类 每天吃奶类，大豆或其制品 常吃适量的鱼，禽，蛋和瘦肉 减少烹调油用量，吃清淡少盐膳食 食不过量，天天运动，保持健康体重 三餐分配要合理，零食要适当 每天足量饮水，合理选择饮料 如饮酒应限量 吃新鲜卫生的食物。
  normal_high: 
    desc: 正常高值
    dietary_advice: 1）.控制每日摄入总热量，维持理想体重，适当增加运动量。2）. 减少钠盐，每日食盐用量以不超过6g为宜，减少烹调用盐量，并少食各种腌制品。3）. 减少膳食脂肪和胆固醇，补充适量动物性蛋白质和大豆蛋白等优质蛋白质，其摄入量应占总能量的15％以上。4）. 多吃蔬菜和水果，蔬菜和水果富含膳食纤维、维生素C。5）. 多吃豆制品、低脂奶补充钾、钙。6）. 忌饮酒、吸烟。不喝浓茶、浓咖啡。
  one_level: 
    desc: Ⅰ级高血压
    dietary_advice: 1）.控制每日摄入总热量，维持理想体重，适当增加运动量。2）. 减少钠盐，每日食盐用量以不超过6g为宜，减少烹调用盐量，并少食各种腌制品。3）. 减少膳食脂肪和胆固醇，补充适量动物性蛋白质和大豆蛋白等优质蛋白质，其摄入量应占总能量的15％以上。4）. 多吃蔬菜和水果，蔬菜和水果富含膳食纤维、维生素C。5）. 多吃豆制品、低脂奶补充钾、钙。6）. 忌饮酒、吸烟。不喝浓茶、浓咖啡。
  two_level: 
    desc: Ⅱ级高血压
    dietary_advice: 1）.控制每日摄入总热量，维持理想体重，适当增加运动量。2）. 减少钠盐，每日食盐用量以不超过6g为宜，减少烹调用盐量，并少食各种腌制品。3）. 减少膳食脂肪和胆固醇，补充适量动物性蛋白质和大豆蛋白等优质蛋白质，其摄入量应占总能量的15％以上。4）. 多吃蔬菜和水果，蔬菜和水果富含膳食纤维、维生素C。5）. 多吃豆制品、低脂奶补充钾、钙。6）. 忌饮酒、吸烟。不喝浓茶、浓咖啡。
  three_level: 
    desc: Ⅲ级高血压
    dietary_advice: 1）.控制每日摄入总热量，维持理想体重，适当增加运动量。2）. 减少钠盐，每日食盐用量以不超过6g为宜，减少烹调用盐量，并少食各种腌制品。3）. 减少膳食脂肪和胆固醇，补充适量动物性蛋白质和大豆蛋白等优质蛋白质，其摄入量应占总能量的15％以上。4）. 多吃蔬菜和水果，蔬菜和水果富含膳食纤维、维生素C。5）. 多吃豆制品、低脂奶补充钾、钙。6）. 忌饮酒、吸烟。不喝浓茶、浓咖啡。

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults