#encoding: utf-8

defaults: &defaults
  normal_diet: 食物多样，谷类为主，粗细搭配 多吃蔬菜水果和薯类 每天吃奶类，大豆或其制品 常吃适量的鱼，禽，蛋和瘦肉 减少烹调油用量，吃清淡少盐膳食 食不过量，天天运动，保持健康体重 三餐分配要合理，零食要适当 每天足量饮水，合理选择饮料 如饮酒应限量 吃新鲜卫生的食物。
  bad_diet: 不吃早餐，晚餐过晚，饮水不足，饮酒过度，饮食过咸、过于油腻，暴饮暴食。
  motion_intensity: 运动量不少于5次/周，每次应不少于30分钟，每次运动在60～90分钟。为宜。
  sport_events: (1)根据空气污染情况，科学地选择锻炼的时间、地点。\n (2)注意不要意外受伤，注意场地、器械安全等。\n (3)运动前充分做好热身活动，运动后注意放松及保暖。\n (4)在运动过程中，要养成运动中补水的习惯，补水的原则是少量多次，建议喝运动饮料或纯净水。\n (5)在进行锻炼时要考虑身体患有某种疾病的因素。\n (6)运动后30分钟内不能进食。因为此时胃肠血管处于收缩状态，进食会影响消化。\n (7)若运动后精神状态好，睡眠好，食欲好，表明运动量合适;反之，若运动后非常疲倦，甚至感到头昏，周身无力，食欲差，睡眠差，则表明运动过度，需要适当减量。
  thin: 
    desc: 偏瘦
    disease: 低（但其它疾病危险性增加）
    dietary_advice: 每天摄入总能量：2000~2700kcal，能量水平：节食，三大营养物占比：蛋白质15%，脂肪25%，碳水化合物60%。
  normal:
    desc: 正常
    disease: '平均水平'
    dietary_advice: ''
  overweight:
    desc: 超重
    disease: ''
    dietary_advice: 每天摄入总能量：1200~1800kcal，能量水平：节食，三大营养物占比：蛋白质25%，脂肪10%，碳水化合物65%。
  fat:
    desc: 偏胖
    disease: 增加
    dietary_advice: 每天摄入总能量：600~1000kcal，能量水平：低能量，三大营养物占比：蛋白质25%，脂肪10%，碳水化合物65%。
  obesity:
    desc: 肥胖
    disease: 严重增加
    dietary_advice: 每天摄入总能量：200~600kcal，能量水平：极低能量，三大营养物占比：蛋白质25%，脂肪10%，碳水化合物65%。

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults